# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'finalproject_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Analytics'
 	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
  pod 'Firebase/Database'
	pod 'IQKeyboardManagerSwift', '6.5.0'
	pod 'DropDown'
	pod 'FSCalendar'
	pod 'Charts'
	pod 'ChartsRealm'
	pod 'MessageKit'
	pod 'MultiProgressView'
  pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :tag => '4.8.0'
  
  pod 'CollectionPickerView'
  

  # Pods for finalproject_1
	# add the Firebase pod for Google Analytics
	
	# add pods for any other desired Firebase products
	# https://firebase.google.com/docs/ios/setup#available-pods
end
